# Standards: 0.11
---

#  5.4.5 Ensure default user shell timeout is 900 seconds or less

- name: 5.4.5 Ensure default user shell timeout is 900 seconds or less
  lineinfile:
    regexp: "^TMOUT\\s+"
    line: "TMOUT={{ cis_tmout_default }}"
    dest: "{{ item }}"
  with_items: "{{ cis_tmout_shell_files }}"
  tags:
    - level-1
    - section-5
    - "5.4.5"
    - scored
